[versions]
plugin-publish = "1.1.0"
docker-java = "3.3.3"
activation = "1.1.1"
asm = "9.6"
spock = "2.0-groovy-3.0"
zt-zip = "1.13"
commons-vfs2 = "2.9.0"

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }

[libraries]
docker-java-core = { module = "com.github.docker-java:docker-java-core", version.ref = "docker-java" }
docker-java-api = { module = "com.github.docker-java:docker-java-api", version.ref = "docker-java" }
docker-java-transport-httpclient5 = { module = "com.github.docker-java:docker-java-transport-httpclient5", version.ref = "docker-java" }
activation = { module = "javax.activation:activation", version.ref = "activation" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
zt-zip = { module = "org.zeroturnaround:zt-zip", version.ref = "zt-zip" }
commons-vfs2 = { module = "org.apache.commons:commons-vfs2", version.ref = "commons-vfs2" }

[bundles]
docker-java = ["docker-java-core", "docker-java-api", "docker-java-transport-httpclient5"]
